import { useState } from "react";
import { X } from "lucide-react";
import { TextField } from "../../components/ui/TextField";
import { CopyButton } from "../../components/ui/CopyButton";
import { FileDrop } from "../../components/ui/FileDrop";
import { useLiveAction } from "../../lib/useLiveAction";
import { useSeed } from "../../lib/seed";
import { useToolState } from "../../lib/toolState";
import { errorMessage } from "../../lib/ipc";
import { readFileAsDataUrl } from "../../lib/file";
import { qrGenerate, qrRead } from "./api";

export function QrTool() {
  const seed = useSeed();
  const [text, setText] = useToolState("input", seed.value);
  const { data: svg, error: genError } = useLiveAction(
    () => (text.trim() === "" ? null : qrGenerate(text)),
    [text],
  );

  const [readResult, setReadResult] = useState<string | null>(null);
  const [readError, setReadError] = useState<string | null>(null);
  const [readImage, setReadImage] = useState<string | null>(null);

  async function onFile(file: File) {
    try {
      const dataUrl = await readFileAsDataUrl(file);
      setReadImage(dataUrl);
      setReadResult(await qrRead(dataUrl));
      setReadError(null);
    } catch (e) {
      setReadError(errorMessage(e));
      setReadResult(null);
    }
  }

  return (
    <div className="grid h-full grid-cols-2 divide-x divide-border">
      <section className="flex min-h-0 flex-col gap-4 overflow-auto p-4">
        <h2 className="text-xs font-medium uppercase tracking-wider text-fg-subtle">
          Generate
        </h2>
        <TextField
          ariaLabel="QR content"
          value={text}
          onChange={setText}
          placeholder="https://hexkit.app"
        />
        {text && (
          <button
            type="button"
            onClick={() => setText("")}
            className="inline-flex w-fit items-center gap-1 rounded-lg border border-border px-2.5 py-1 text-xs text-fg-muted transition-colors hover:border-border-strong hover:text-accent"
          >
            <X className="size-3.5" />
            Clear
          </button>
        )}
        {genError ? (
          <p className="text-sm text-accent">{genError}</p>
        ) : svg ? (
          <div className="flex flex-col items-start gap-3">
            <div
              className="w-48 rounded-xl border border-border bg-white p-3"
              // SVG is generated by our own backend, so it is safe to inline.
              dangerouslySetInnerHTML={{ __html: svg }}
            />
            <CopyButton value={svg} label="Copy SVG" />
          </div>
        ) : null}
      </section>

      <section className="flex min-h-0 flex-col gap-4 overflow-auto p-4">
        <h2 className="text-xs font-medium uppercase tracking-wider text-fg-subtle">
          Read
        </h2>
        <FileDrop
          accept="image/*"
          inputLabel="QR image"
          label="Drop, paste, or click to choose a QR image"
          hint="Or paste a screenshot with ⌘/Ctrl+V"
          typeErrorMessage="That doesn't look like an image. Paste or drop a QR-code image."
          previewUrl={readImage ?? undefined}
          onFile={onFile}
          onClear={() => {
            setReadImage(null);
            setReadResult(null);
            setReadError(null);
          }}
        />
        {readError ? (
          <p className="text-sm text-accent">{readError}</p>
        ) : readResult !== null ? (
          <div className="flex items-center gap-3 rounded-xl border border-border bg-surface px-4 py-3">
            <span className="min-w-0 flex-1 break-all font-mono text-sm text-fg">
              {readResult}
            </span>
            <CopyButton value={readResult} label="" />
          </div>
        ) : (
          <p className="text-sm text-fg-subtle">
            Upload an image containing a QR code to decode it.
          </p>
        )}
      </section>
    </div>
  );
}
