import { useState, type ChangeEvent } from "react";
import { Upload } from "lucide-react";
import { TextField } from "../../components/ui/TextField";
import { CopyButton } from "../../components/ui/CopyButton";
import { useLiveAction } from "../../lib/useLiveAction";
import { useSeed } from "../../lib/seed";
import { errorMessage } from "../../lib/ipc";
import { readFileAsDataUrl } from "../../lib/file";
import { qrGenerate, qrRead } from "./api";

export function QrTool() {
  const seed = useSeed();
  const [text, setText] = useState(seed.value);
  const { data: svg, error: genError } = useLiveAction(
    () => (text.trim() === "" ? null : qrGenerate(text)),
    [text],
  );

  const [readResult, setReadResult] = useState<string | null>(null);
  const [readError, setReadError] = useState<string | null>(null);

  async function onFile(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    try {
      const dataUrl = await readFileAsDataUrl(file);
      setReadResult(await qrRead(dataUrl));
      setReadError(null);
    } catch (e) {
      setReadError(errorMessage(e));
      setReadResult(null);
    }
  }

  return (
    <div className="grid h-full grid-cols-2 divide-x divide-border">
      <section className="flex min-h-0 flex-col gap-4 overflow-auto p-4">
        <h2 className="text-xs font-medium uppercase tracking-wider text-fg-subtle">
          Generate
        </h2>
        <TextField
          ariaLabel="QR content"
          value={text}
          onChange={setText}
          placeholder="https://hexkit.app"
        />
        {genError ? (
          <p className="text-sm text-accent">{genError}</p>
        ) : svg ? (
          <div className="flex flex-col items-start gap-3">
            <div
              className="w-48 rounded-xl border border-border bg-white p-3"
              // SVG is generated by our own backend, so it is safe to inline.
              dangerouslySetInnerHTML={{ __html: svg }}
            />
            <CopyButton value={svg} label="Copy SVG" />
          </div>
        ) : null}
      </section>

      <section className="flex min-h-0 flex-col gap-4 overflow-auto p-4">
        <h2 className="text-xs font-medium uppercase tracking-wider text-fg-subtle">
          Read
        </h2>
        <label className="inline-flex w-fit cursor-pointer items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs text-fg-muted transition-colors hover:border-border-strong hover:text-fg">
          <Upload className="size-3.5" />
          Choose image
          <input
            type="file"
            accept="image/*"
            aria-label="QR image"
            className="hidden"
            onChange={onFile}
          />
        </label>
        {readError ? (
          <p className="text-sm text-accent">{readError}</p>
        ) : readResult !== null ? (
          <div className="flex items-center gap-3 rounded-xl border border-border bg-surface px-4 py-3">
            <span className="min-w-0 flex-1 break-all font-mono text-sm text-fg">
              {readResult}
            </span>
            <CopyButton value={readResult} label="" />
          </div>
        ) : (
          <p className="text-sm text-fg-subtle">
            Upload an image containing a QR code to decode it.
          </p>
        )}
      </section>
    </div>
  );
}
